
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author menna
 */
public class gui extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Rows = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        Cols = new javax.swing.JSpinner();
        resetBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        resetBtn.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ROWS");
        jPanel1.add(jLabel1);

        Rows.setValue(0);
        Rows.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RowsStateChanged(evt);
            }
        });
        jPanel1.add(Rows);

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("COLUMNS");
        jPanel1.add(jLabel2);

        Cols.setValue(0);
        Cols.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ColsStateChanged(evt);
            }
        });
        jPanel1.add(Cols);

        resetBtn.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        resetBtn.setText("Reset");
        resetBtn.setMargin(new java.awt.Insets(4, 14, 2, 14));
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        jPanel1.add(resetBtn);

        getContentPane().add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 103, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
           initalizePuzzle();
    }//GEN-LAST:event_resetBtnActionPerformed

    
    private static Icon resizeIcon(ImageIcon icon, int resizedWidth, int resizedHeight) {
    Image img = icon.getImage();  
    Image resizedImage = img.getScaledInstance(resizedWidth, resizedHeight,  java.awt.Image.SCALE_SMOOTH);  
    return new ImageIcon(resizedImage);
}
    
    private JButton createPuzzleItem(){
           JButton btn = new JButton();    //btn.setPreferredSize(new Dimension(60,60));
                    btn.setMinimumSize(new Dimension(90,90));
                    btn.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                              //btn.setText("Clicked!");
                           //   btn.getSize().height;
                           Icon icon = (btn.getIcon() == null)?resizeIcon(new ImageIcon("bomb.png"),80,80):null;
                            btn.setIcon(icon);
                            }
        });
                    jPanel2.add(btn);
            return btn;
         }
    
    
    private void initalizePuzzle(){
        int x=  (Integer) Rows.getValue(); int y=  (Integer) Cols.getValue();  
        jPanel2.setBorder(BorderFactory.createEmptyBorder(10, 20,10,20));
        buttons = new JButton[x][y];
           // jPanel2.add(btn,0,0);
           // jPanel2.add(btn,1,0);
            jPanel2.removeAll();
            //jPanel2.add(btn,0,2);
            for(int i=0;i<x;i++){
                for(int j=0; j<y; j++){ 
                    buttons[i][j]= createPuzzleItem();
                    
                }
            }          
              jPanel2.setLayout(new GridLayout(x,y,10,10));
              jPanel2.revalidate(); jPanel2.repaint(); jPanel2.updateUI();
}
    private void ColsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ColsStateChanged
        initalizePuzzle();
    }//GEN-LAST:event_ColsStateChanged

    private void RowsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RowsStateChanged
        initalizePuzzle();
// TODO add your handling code here:
    }//GEN-LAST:event_RowsStateChanged

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }
    public JPanel getPanel(){return jPanel1;}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Cols;
    private javax.swing.JSpinner Rows;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton resetBtn;
    // End of variables declaration//GEN-END:variables
    private JButton[][] buttons;
}
